### ISSUE TITLE
Formatar README usando Markdown

### ISSUE THREAD

**Issue by lhsazevedo** [gilsonhenrique/Oficina-perfeita-Combustao#2]
Markdown é uma linguagem simples de marcação que permite a formatar textos com títulos, listas, negrito, itálico etc.

O GitHub aceita Markdown, basta mudar a extensão do seu README de `.txt` para `.md`.
Depois, é só editar seu arquivo adicionando títulos e outras formatações da maneira que preferir.

Para saber mais sobre a sintaxe do Markdown, confira [este guia](https://docs.github.com/pt/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) disponibilizado pelo GitHub.

Alguns repositórios para se inspirar:
https://github.com/souzacristsf/eReports-open-source
https://github.com/tarsodecastro/geradoc
https://github.com/puppe1990/ControleEstoque
https://github.com/danielromeroauk/inventarios
https://github.com/JohnatanT/PetShopAdmin

---

Exemplo e resultado:

Texto:
```
# Título nível 1
## Título nível 2
### Título nível 3

Texto com *itálico*, **negrito** e ~~tachado~~.
Emojis também são suportados :rocket: 

Uma lista:
- Primeiro item
- Segundo item
- Terceiro item
```
Resultado:
# Título nível 1
### Título nível 3

Texto com *itálico*, **negrito** e ~~tachado~~.
Emojis também são suportados :rocket:

Uma lista:
- Primeiro item
- Segundo item
- Terceiro item

**Comment by gilsonhenrique** [comment]
Obrigado
